<?php
session_start();

if (isset($_SESSION['id']) && isset($_SESSION['user_name'])) {

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Java Script</title>
    <link rel="stylesheet" href="css/hamburger.css">
    <link rel="stylesheet" href="css/porfotlio.css">
    <link rel="stylesheet" href="css/navigation.css">
<style>
</style>
</head>
<body>
<container>
<headfloat>
            <header>
            <a href="main.php" class="logo">JN GS</a>
            <div class="group">
                <ul class="navigation">
                    <li><a href="main.php">Home</a></li>
                    <li><a href="tools.php">Tools</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="logout.php">Logout</a></li>
                </ul>
                <div class="search">
                    <span class="icon">
                        <ion-icon name="search-outline" class="searchBtn"></ion-icon>
                        <ion-icon name="close-outline" class="closeBtn"></ion-icon>
                    </span>
                </div>
                <ion-icon name="menu-outline" class="menuToggle"></ion-icon>
            </div>
            <div class="searchBox">
                <input type="text" placeholder="Search...">
            </div>
            </header>

            <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
                <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
                <script src="js/navigation.js"></script>
</headfloat>
</container>

    <margintop></margintop>

    <container2>
        <table>
            <td>
                <a href="main.php"><text1>&lt;</text1></a>
            </td>
            <td>
                <text1>What is JavaScript?</text1>
            </td>
        </table>
    </container2>

        <main2>
            <text2>
            JavaScript is a dynamic computer programming language. 
            </text2>
        </main2>

        

    <!-- This is for JS Examples -->
<content1>
<text type="button" onclick="document.getElementById('details').style.display='block'">It is lightweight and most commonly used as a part of web pages whose implementations allow client-side script to interact with the user and make dynamic pages.</text>
    <div class="jsresult">
        <text5>
            <div contenteditable="true">
            <p id="details" style="display:none">
            It is an interpreted programming language with object-oriented capabilities. <br/>
            JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the 
            excitment being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. 
            The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('overview').style.display='block'"><text3>1. Overview</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="overview" style="display:none">
            The ECMA-262 Specification defined a standard version of the core JavaScript language. <br/>
            * JavaScript is a lightweight,interpreted programming language.<br/>
            * Designed for creating network-centric applications.<br/>
            * Complementary to and integrated with Java.<br/>
            * Complementary to and integrated with Html.<br/>
            * Open and cross-platform. <br/><br/>

            <a href="jsoverview.php">
                Client-Side JavaScript,<br/> Advantages of JavaScript,<br/> Limitations of JavaScript,<br/> 
                JavaScript Development tools,<br/> Where is JavaScript today
            </a>
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('syntax').style.display='block'"><text3>2. Syntax</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="syntax" style="display:none">
            You can place the < s c r i p t > &nbsp; tags, containing your JavaScript, anywhere within your web page, but it is normally recommended that you should keep it within the < h e a d > &nbsp; tags... <a href="jssyntax.php">More</a> &nbsp; &gt;
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('enabling').style.display='block'"><text3>3. Enabling</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="enabling" style="display:none">
            All the modern browsers come with built-in support for JavaScript. Frequently, you may need to enable or disable this 
            support manually . . . <a href="jsenabling.php">More</a> &nbsp; &gt;
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('placement').style.display='block'"><text3>4. Placement</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="placement" style="display:none">
            There is a flexibility given to include JavaScript code anywhere in an HTML document. However . . . <a href="jsplacement.php">More</a> &nbsp; &gt;
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('variables').style.display='block'"><text3>5. Variables</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="variables" style="display:none">
            . . . <a href="jsvariables.php">More</a> &nbsp; &gt;
            </p>
            </div>
        </text5>
    </div>

<text type="button" onclick="document.getElementById('operators').style.display='block'"><text3>6. Operators</text3></text>
    <div class="jsresult">
        <text5>
            <div contenteditable="false">
            <p id="operators" style="display:none">
            What is Operators? Let us take a simple expression 4 + 5 is equal to 9. Here 4 and 5 are called operands and '+' is called the operator . . . <a href="jsoperators.php">More</a> &nbsp; &gt;
            </p>
            </div>
        </text5>
    </div>
</content1>

    <script src="js/hamburger.js"></script>

    <footer>
        Copyright &copy; 2023 <NAME>JN GS</NAME>
    </footer>
</body>
</html>

<?php
}else{
    header("Location: index.php");
    exit();
}
?>